site_name: Timechainswap Docs
site_description: Documentations Of Timechainswap 
site_url: https://timechainswap.com/
repo_url: https://github.com/Timechainapp
repo_name: Timechainswap
theme:
  name: material
  custom_dir: overrides
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: deep purple
    accent: dark blue
    toggle:
      icon:  material/weather-sunny
      name: Switch to light mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: purple
    accent: light blue
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
  - navigation.tabs
  icon:
    repo: fontawesome/brands/github-alt
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  logo: img/icon-white.svg
  favicon: img/favicon.png
  language: en
edit_uri: ''
plugins:
  - search
  - drawio-exporter
      # drawio_args:
      #     - --no-sandbox
  # - drawio-exporter:
  #     # cache_dir: '.drawio-exporter-cache'
  #     drawio_executable: null
  #     drawio_args: 
  #       - "--no-sandbox"
  #       - "--border 10"
  #     # use 'jpg' here if you see bad image icons in export
  #     format: svg
  #     sources: '*.drawio'
  - inline-svg
markdown_extensions:
- toc:
    permalink: true
- markdown.extensions.codehilite:
    guess_lang: false
- mdx_include:
    base_path: docs
- admonition
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.superfences:
    preserve_tabs: true
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format ''
- pymdownx.tabbed:
    alternate_style: true
# TODO Add google analytics ...
# extra:
#   analytics:
#     provider: google
#     property: UA-133183413-1
extra_css:
- css/termynal.css
- css/custom.css
extra_javascript:
- js/termynal.js
- js/custom.js
- optionalConfig.js
- https://unpkg.com/mermaid@8.8.4/dist/mermaid.min.js
- extra-loader.js

nav:
- Timechain: index.md
- Services:
  - Aggregator: 
    - Services/Aggregator/index.md
    - Core:
      - Protocols: 
        - Services/Aggregator/Models/index.md
        - Services/Aggregator/Protocols/index.md
        - Services/Aggregator/Protocols/Amm.md
        - Services/Aggregator/Protocols/Beethoven.md
        - Services/Aggregator/Protocols/Curve.md
      - Background :
        - Services/Aggregator/BackGroundTasks/index.md
        - Services/Aggregator/BackGroundTasks/DgraphRelated/index.md
        - Services/Aggregator/BackGroundTasks/DgraphRelated/create_facets.md
        - Services/Aggregator/BackGroundTasks/DgraphRelated/filter_facets.md
        - Services/Aggregator/BackGroundTasks/DgraphRelated/filter_pairs.md
        - Services/Aggregator/BackGroundTasks/DgraphRelated/filter_tokens.md
        - Services/Aggregator/BackGroundTasks/DgraphRelated/insert_chains.md
        - Services/Aggregator/BackGroundTasks/DgraphRelated/insert_dexes.md
        - Services/Aggregator/BackGroundTasks/DgraphRelated/insert_pairs.md
        - Services/Aggregator/BackGroundTasks/DgraphRelated/insert_prices.md
        - Services/Aggregator/BackGroundTasks/DgraphRelated/insert_tokens.md
        - Services/Aggregator/BackGroundTasks/DgraphRelated/update_pairs.md
      - Configs:
        - Services/Aggregator/Configs/dgraph_config.md
      - Database Related:
        - Services/Aggregator/Databases/index.md
        - Services/Aggregator/Databases/Dgraph/index.md
        - Services/Aggregator/Databases/Dgraph/dgraph_built_in.md
        - Services/Aggregator/Databases/Dgraph/dgraph_client.md
        - Services/Aggregator/Databases/Redis/index.md
        - Services/Aggregator/Databases/Redis/redis_client.md
      - Logic:
        - Services/Aggregator/Logic/best_path.md
        - Services/Aggregator/Logic/find_and_swap.md
        - Services/Aggregator/Logic/init_find.md
        - Services/Aggregator/Logic/middleware.md
        - Services/Aggregator/Logic/path.md
        - Services/Aggregator/Logic/portioning.md
        - Services/Aggregator/Logic/should_unwrap.md
        - Services/Aggregator/Logic/should_wrap.md
    - Diagrams:
      - Versions:
          - Services/Aggregator/Version-1.md
          - Services/Aggregator/Version-2.md
  - AggregatorOfAggregators:
    - Services/AggregatorOfAggregators/index.md
    - Services/AggregatorOfAggregators/api.md
    - Services/AggregatorOfAggregators/ui.md
  - Bridge:
      - Services/Bridge/api.md
      - Services/Bridge/event.md
      - PaymentsService:
          - Services/Bridge/PaymentsService/base.md
          - Services/Bridge/PaymentsService/open_payment.md
          - Services/Bridge/PaymentsService/pending_payment.md
          - Services/Bridge/PaymentsService/sending_payment.md
          - Services/Bridge/PaymentsService/refund_payment.md
  - Buyback:
    - Services/Buybacking/index.md

  - Dex:
    -  Services/Dex/Airdrop/index.md
  - Buyback:
    - Services/Buybacking/index.md
- Services/Development-timeline.md
